import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    en: {
        // Header & Nav
        system_title: 'Issue Tracking System',
        dashboard: 'Dashboard',
        analytics: 'Analytics',
        search_placeholder: 'Search issues or locations...',
        search_analytics_placeholder: 'Search recent issue activity...',
        search_calendar_placeholder: 'Search tasks, dates, departments...',
        tasks_found_across_dates: 'tasks found across dates',
        no_tasks_found: 'No tasks found',
        jump_to_date: 'Jump to date',
        status_finished: 'Finished',
        status_unfinished: 'Active / Unfinished',
        period: 'Period',
        export_pdf: 'Export PDF',
        export_report: 'Export Report',
        export_format_pdf: 'PDF Document',
        export_format_excel: 'Excel (.xlsx)',
        download_excel: 'Download Excel (.xlsx)',
        generating_excel: 'Generating Excel...',
        export_calendar_pdf: 'Export Calendar Schedule to PDF',
        export_calendar_pdf_desc: 'Configure schedule filters on the left and preview your PDF report on the right.',
        schedule_period: 'Schedule Period',
        current_month: 'Current Month',
        next_month: 'Next Month',
        all_scheduled: 'All Scheduled',
        custom_range: 'Custom Range',
        task_status: 'Task Status',
        grouping_and_order: 'Grouping & Order',
        group_by_dept: 'Group by Department',
        chronological: 'Chronological by Date',
        report_options: 'Report Options',
        include_kpi_summary: 'Show Summary KPI Cards',
        include_notes_column: 'Include Task Notes Column',
        tasks_selected: 'tasks selected',
        generating_preview: 'Rendering PDF preview...',
        download_pdf: 'Download PDF',
        downloading: 'Downloading...',
        send_via_email: 'Send via Email',
        email_report_title: 'Send Report via Email',
        email_recipients: 'Recipients',
        email_recipients_placeholder: 'Type an email and press Enter or comma...',
        quick_select_recipients: 'Quick Select Recipients',
        all_hods: 'All HODs',
        my_department: 'My Department',
        email_subject: 'Subject',
        email_subject_placeholder: 'Email subject...',
        email_message: 'Personal Note (Optional)',
        email_message_placeholder: 'Add any additional notes for the recipients...',
        sending_email: 'Sending Email...',
        send_email_button: 'Send Email',
        email_sent_success: 'Report successfully sent via email!',
        email_send_failed: 'Failed to send email. Please check your connection and configuration.',
        attached_pdf: 'Attached PDF',
        no_recipients_selected: 'Please select or add at least one recipient email.',
        google_connected_banner: 'Sending directly from your Google Account:',
        google_not_connected_banner: 'Sending via Telunas System Mailer',
        connect_google_button: 'Connect Google',
        disconnect_google: 'Disconnect',
        connect_google_hint: 'Connect your Google account to send reports directly from your real Gmail.',
        select_multiple_hint: 'Can select more than 1',
        emergency: 'EMERGENCY',
        report_issue: 'Report Issue',
        profile: 'Profile',
        
        // Dashboard Page
        facility_dashboard: 'Community facility dashboard',
        dashboard_desc: "Report what's broken, claim a job, and log the fix — connected directly to Google Sheets.",
        sync_sheets: 'Sync Sheets',
        total_reports: 'Total Reports',
        needs_fixing: 'Needs Fixing',
        in_progress: 'In Progress',
        resolved: 'Resolved',
        
        // Overdue Alert
        overdue_alert: 'OVERDUE CRITICAL ISSUES',
        unclaimed: 'Unclaimed',
        unmute_alarm: 'Unmute Alarm',
        sound_active: 'Sound Active (Click to Mute)',

        // Filters
        category: 'Category',
        department: 'Department',
        all: 'All',
        open: 'Open',
        pending: 'Pending',
        solved: 'Solved',
        all_categories: 'All Categories',
        all_departments: 'All Departments',
        filter_by_category: 'Filter by Category',
        filter_by_dept: 'Filter by Department',

        // Issue Card
        original_problem: 'Original Problem',
        reported_by: 'Reported by',
        currently_pending: 'Currently pending by',
        claim_job: 'Claim Job',
        resolve_issue: 'Resolve Issue',
        view_details: 'View Details',
        solved_details: 'Solved Details',

        // Modals
        report_new_issue: 'Report New Issue',
        report_emergency: 'Report EMERGENCY Issue',
        location: 'Location',
        title: 'Title / Description',
        priority: 'Priority',
        photo: 'Photo',
        submit: 'Submit Report',
        cancel: 'Cancel',

        // Analytics
        performance_analytics: 'Performance & Resolution Analytics',
        analytics_desc: 'Comprehensive breakdown of resort maintenance metrics, response times, and team performance.',
        response_time: 'Avg Response Time',
        resolution_rate: 'Resolution Rate',
        critical_issues: 'Critical Issues',
        department_breakdown: 'Department Breakdown',
        category_distribution: 'Category Distribution',

        // Analytics Page
        issues_by_category: 'Issues by Category',
        issues_by_department: 'Issues by Department',
        finished_status: 'Finished',
        still_being_done: 'Still Being Done',
        total_issues: 'Total Issues',
        no_data: 'No data available',
        recent_activity: 'Recent Issue Activity',
        no_recent_activity: 'No recent activity.',
        show: 'Show',
        items: 'Items',
        all_items: 'All',
        date_na: 'Date N/A',
        critical: 'Critical',
        by_reporter: 'by',
        photo_pending: '📷 Pending photo',
        photo_report: '📷 Report photo',
        select_sheets: 'Select Data Sheets',
        combine_sheets_desc: 'Select one or more sheets to view combined analytics across multiple periods.',
        all_sheets: 'All Sheets',
        combining_sheets: 'Combining',
        sheets_label: 'sheets',
        active_issues_count: 'issues loaded',
        time_range: 'Time Range',
        filter_time_range: 'Filter by Time Range',
        all_time: 'All Time',
        today: 'Today',
        days_3: '3 Days',
        days_7: '7 Days',
        week_1: '1 Week',
        weeks_2: '2 Weeks',
        weeks_3: '3 Weeks',
        weeks_4: '4 Weeks',
        month_1: '1 Month',
        months_3: '3 Months',
        months_6: '6 Months',
        showing_filtered_range: 'Showing data for',

        // Departments & Assignment
        origin_department: 'Origin Department',
        assigned_departments: 'Assigned Department(s)',
        assigned_to: 'Assigned To',
        responsible_to_fix: 'Responsible to fix',
        tagged_departments: 'Tagged Department(s)',
        tagged_info_only: 'Tagged (Info / Notification only)',
        select_assigned_depts: 'Select department(s) responsible for fixing this issue',
        select_tagged_depts: 'Select department(s) to notify for awareness / FYI only',
        dept_filter_mode: 'Filter Mode',
        dept_mode_assigned: 'Assigned Dept',
        dept_mode_origin: 'Origin Dept',
        dept_mode_tagged: 'Tagged Dept',
        dept_mode_all: 'All Related',
        all_my_scope: 'All Scope',
        to_fix: 'To Fix',
        reported_by_me: 'My Reports',
        mentioned_me: 'Mentions',
        dept_mode_incoming: 'Incoming (To Fix)',
        dept_mode_outgoing: 'Outgoing (Requested)',
        dept_mode_all_scope: 'All Scope',
        dept_perspective_title: 'Department Perspective',
        dept_perspective_desc: 'Showing your department’s interactions with other teams.',
        tooltip_incoming_dept: '📥 Incoming: Shows which departments requested help or assigned tickets to your department.',
        tooltip_outgoing_dept: '📤 Outgoing: Shows which departments are tasked to fix issues reported by your department.',
        tooltip_dept_all_scope: '🌐 All Scope: Shows all partner departments interacting with your department.',

        // Operations Page
        operations: 'Operations',
        select_department: 'Select Department',
        total_work: 'Total Work',
        active_work: 'Active Work',
        done_work: 'Completed',
        pending_work: 'Pending / Issues',
        refresh: 'Refresh',
        add_work: 'Add Work',
        add_work_for: 'Add Work —',
        edit_work: 'Edit Work',
        all_sources: 'All',
        source_issues: '🔧 Issues Tracker',
        source_manual: '📋 Department Tasks',
        select_sheets: 'Sheets / Periods',
        all_sheets: 'All Sheets',
        sheets_selected: 'selected',
        combined_sheets: 'Combined',
        loading_dept_data: 'Loading department data…',
        no_active_work: 'No active work items',
        no_active_work_desc: 'Click "+ Add Work" to log tasks for this department',
        work_title: 'Work Title',
        work_title_placeholder: 'e.g. Hammock repair near Villa 01',
        work_desc: 'Description / Details',
        work_desc_placeholder: 'Details about the maintenance or operational task…',
        work_location: 'Location',
        work_location_placeholder: 'e.g. Villa 01, Pool Deck, Main Jetty',
        specific_location_in: 'Detail in',
        start_date: 'Start Date',
        end_date: 'Est. Completion Date',
        priority_level: 'Priority',
        priority_low: 'Low',
        priority_normal: 'Normal',
        priority_urgent: 'Urgent',
        priority_high: 'High',
        photo_optional: 'Upload Photo (optional)',
        notes: 'Notes',
        notes_placeholder: 'Additional notes or remarks…',
        save_work: 'Save Work',
        save_changes: 'Save Changes',
        saving: 'Saving…',
        mark_done: 'Done',
        edit: 'Edit',
        delete: 'Delete',
        confirm_delete_work: 'Delete this work item?',
        created_at: 'Created',
        completed_at: 'Completed',
        from_dept: 'from',
        claimed_at: 'Claimed',
        pending_reason_title: 'Pending Reason / Delay History',
        pending_by: 'Delayed by',
        no_reason_provided: 'No reason provided.',
        origin_badge: 'Origin',
        assigned_badge: 'Assigned',
        tagged_badge: 'Tagged',
        manual_badge: 'TASK',
        issue_badge: 'ISSUE',
        status_active: 'Active',
        status_needs_fixing: 'Needs Fixing',
        status_in_progress: 'In Progress',
        total_items_displayed: 'displayed',
        work_summary_total: 'total work',
        work_summary_active: 'active',
        work_summary_done: 'completed',
        work_timeline: 'Work Timeline & Schedule',
        timeline_schedule: 'Timeline & Schedule',
        days_remaining: 'days remaining',
        day_remaining: 'day remaining',
        days_overdue: 'days overdue',
        due_today: 'Target: Today',
        starts_in: 'Starts in',
        calendar: 'Calendar',
        calendar_view: 'Calendar',
        list_view: 'List View',
        calendar_mode: 'Calendar Mode',
        tasks_on_date: 'Tasks on',
        task_unit: 'Tasks',
        task_unit_singular: 'Task',
        day_progress: 'Day {x} of {y}',
        no_tasks_on_date: 'No operations or tasks scheduled on this day',
        no_departments_selected: '0 Departments Selected',
        single_day_task: 'Single-day task',
        today_btn: 'Today',
        add_work_on_date: 'Add Task on this Date',
        selected_day_agenda: 'Day Agenda',
        active_dept_calendar: 'Calendar Schedule for',
        click_date_to_view: 'Click any date to inspect scheduled operations',
        add_date_range: 'Add Date Range',
        schedule_blocks: 'Schedule Blocks',
        drag_hint_desktop: '💡 Drag across dates with mouse to select a date range',
        drag_calendar_tip: '💡 Drag on the calendar to select or add date blocks',
        skipping_dates: 'Skipping',
        date_block: 'Block',
        block_start: 'From',
        block_end: 'To',
        focusing_on_task: 'Focusing on Task',
        show_all_tasks: 'Show All Tasks',
        task_focused_grid: 'Focused on Calendar',
        click_card_to_view_grid: 'Click block to filter dates',
        click_block_to_filter: 'Click block to filter dates',
        all_blocks: 'All Blocks',
        view_by_date: 'Date',
        all_tasks_scope: 'All Tasks',
        back_to_date: 'Back to Date',
        months_label: 'Months',
        month_label: 'Month',
        all_time: 'All Time',
        clear_dates: 'Clear All Dates',
        clear: 'Clear',
        profile: 'Profile',
        logout: 'Log Out',
        account_settings: 'Account & Security',
        account_info: 'Account Information',
        change_password: 'Change Password',
        current_password: 'Current Password',
        new_password: 'New Password',
        confirm_password: 'Confirm New Password',
        password_changed_success: 'Password updated successfully.',
        role_label: 'Account Role',
        department_label: 'Department Scope',
        subdivision_label: 'Sub-Division',
        staff_name_label: 'Display Name',
        email_label: 'Email Address',
        confirm_logout_msg: 'Are you sure you want to log out from this device?',
        logging_out: 'Logging out...',

        // Locked Identity & Modals
        locked_to_department: 'Department Scope',
        claiming_department: 'Claiming Department',
        staff_name: 'Staff Name',
        assigned_staff: 'Assigned Staff',
        resolver_staff: 'Resolver Staff',
        delay_staff: 'Delay Reported By',
        monitor_mode_title: 'Monitor Mode (View Only)',
        monitor_mode_desc: 'This issue is assigned to other departments. Only assigned departments can claim or resolve this ticket.',
        step_dept_delay: 'Step 1 — Delay Reported By (Dept)',
        step_dept_resolve: 'Step 1 — Resolved By (Dept)',
        step_worker_delay: 'Step 2 — Worker Name',
        step_worker_resolve: 'Step 2 — Solver Name',
        proof_of_delay: 'Proof of delay',
        proof_of_fix: 'Proof of fix',
        upload_proof_delay: 'Upload proof of delay',
        upload_proof_fix: 'Upload proof photo',
        confirm_pending: 'Confirm Pending',
        mark_as_solved: 'Mark as Solved',
        marking_pending: 'Marking as Pending...',
        saving_fix: 'Saving Fix & Uploading...',
        cancel_pending_btn: 'Cancel Pending, Mark Solved instead',
        mark_pending_btn: 'Problem during fix? Mark as Pending',
        close_btn: 'Close',
        all_my_scope: 'All My Scope',
        to_fix: 'To Fix',
        reported_by_me: 'Reported By Me',
        mentioned_me: 'Mentioned Me',

        // Schedule Conflict Warning
        schedule_conflict_title: 'Department Schedule Notice',
        schedule_conflict_desc: 'The following department(s) are currently scheduled for active tasks today:',
        schedule_conflict_confirm_title: 'Confirm Assignment With Busy Department(s)',
        schedule_conflict_confirm_msg: 'The department(s) you tagged/assigned have active scheduled tasks during this timeframe. Are you sure you want to assign this issue to them?',
        assign_anyway_btn: 'Yes, Assign Anyway',
        review_assignment_btn: 'Review Departments',
        currently_busy_with: 'Currently busy with',
        active_task: 'Active Task',

        // Tooltip Explanations
        tooltip_assigned_dept: '🎯 Assigned Dept: Shows workload based on which department is tasked to repair/fix the issue.',
        tooltip_origin_dept: '🏠 Origin Dept: Shows which department discovered and reported the issue.',
        tooltip_tagged_dept: '📢 Tagged Dept: Shows departments looped in for coordination, notification, or assistance.',
        tooltip_all_related_dept: '🌐 All Related: Shows total involvement across reporting, fixing, or tagged roles.',
        tooltip_sheet_selector: 'Select or combine data sheets across different periods/years.',
        tooltip_time_range: 'Filter issues by the timeframe they were reported.',
        tooltip_dept_limit: 'Choose how many top departments to display in the chart.',
        tooltip_export_pdf: 'Generate and download a clean PDF summary of current analytics.',
        tooltip_emergency_btn: 'Report an urgent critical breakdown with alarm notification.',
        tooltip_report_btn: 'Create a new maintenance or facility issue report.',
        tooltip_period_btn: 'Select, create, or manage Google Sheets data periods.',
        tooltip_claim_btn: 'Assign this ticket to yourself to begin the repair.',
        tooltip_pending_btn: 'Pause ticket if waiting for parts or specialized assistance.',
        tooltip_resolve_btn: 'Upload after-photo proof and mark ticket as completed.',
        tooltip_today_btn: 'Jump view to current month and today’s date.',
        tooltip_prev_month: 'View previous month schedule.',
        tooltip_next_month: 'View next month schedule.',

        // Profile WhatsApp Linking
        whatsapp_linking_title: 'WhatsApp Integration & Auto-Recognition',
        whatsapp_number_label: 'Your WhatsApp Number',
        save_whatsapp_btn: 'Save & Link Number',
        update_whatsapp_btn: 'Update WhatsApp Number',
        unlink_whatsapp_btn: 'Unlink WhatsApp Number',

        // Ticketing System
        tickets: 'Tickets',
        approval_tickets: 'Approval Tickets',
        ticket_center_title: 'Ticket Approval Center',
        ticket_admin_badge: 'ADMINISTRATOR — FINAL ACC',
        ticket_hod_badge: 'HOD',
        ticket_staff_badge: 'STAFF',
        ticket_admin_desc: 'Central approval hub for all departments across Telunas Resort. Final authority to activate accounts, WhatsApp bot linking, and password resets.',
        ticket_hod_desc: 'Review and verify requests from your department staff before forwarding them to Admin for final ACC.',
        ticket_staff_desc: 'Track the status of your WhatsApp bot linking and account password reset requests in real-time.',
        ticket_pending_admin_acc: 'Needs Final ACC',
        ticket_approved_count: 'Approved',
        ticket_hod_review_count: 'HOD Review',
        ticket_my_tickets: 'My Tickets',
        ticket_active_tickets: 'Active Tickets',
        ticket_total_requests: 'Total Requests',
        ticket_two_tier_title: 'Two-Tier Approval Workflow:',
        ticket_two_tier_flow: '1. Staff Request ➔ 2. Dept HOD Verification ➔ 3. Admin Final ACC',
        ticket_two_tier_flow_short: 'Staff ➔ HOD ➔ Admin ACC',
        ticket_banner_admin: 'You hold full authority to grant Final ACC & execute changes directly to the live system.',
        ticket_banner_hod: 'You are authorized to review and recommend tickets from your department to Admin.',
        ticket_banner_staff: 'Contact your HOD or Admin if your application requires urgent attention.',
        ticket_all_status: 'All Statuses',
        ticket_status_pending_hod: 'Pending HOD',
        ticket_status_pending_admin: 'Needs Admin ACC',
        ticket_status_waiting_admin: 'Pending Admin',
        ticket_status_approved: 'Approved (ACC)',
        ticket_status_rejected: 'Rejected',
        ticket_all_types: 'All Types',
        ticket_type_account_reg: 'Account Registration',
        ticket_type_wa_change: 'Change WhatsApp',
        ticket_type_wa_unlink: 'Unlink WhatsApp',
        ticket_type_pwd_reset: 'Reset Password',
        ticket_type_dept_transfer: 'Department Transfer',
        ticket_search_placeholder: 'Search ticket #, staff, email...',
        ticket_refresh_btn: 'Refresh',
        ticket_export_pdf_btn: 'Export PDF',
        ticket_sync_sheet_btn: 'Sync Sheet',
        ticket_open_sheet_btn: 'Open Google Spreadsheet',
        ticket_empty_title: 'No Tickets Found',
        ticket_empty_staff: 'You do not have any active ticket history (WhatsApp change or password reset).',
        ticket_empty_filter: 'No ticket requests match the current filter criteria.',
        ticket_submitted_at: 'Submitted',
        ticket_applicant: 'Applicant',
        ticket_request_detail: 'Request Details',
        ticket_requested_wa: 'Requested WhatsApp Number',
        ticket_old_wa: 'Previous Number',
        ticket_requested: 'Requested',
        ticket_unlink_number: 'Unlink Number',
        ticket_pwd_reset_title: 'Password Reset Request',
        ticket_pwd_reset_hint: 'A new secure temporary password will be generated automatically upon Admin ACC.',
        ticket_origin_dept: 'Origin',
        ticket_target_dept: 'Destination',
        ticket_reason_label: 'Reason',
        ticket_audit_trail: 'Verification Trail',
        ticket_step_hod: '1. HOD Review',
        ticket_step_admin: '2. Admin Final ACC',
        ticket_completed: 'Done',
        ticket_by_label: 'By',
        ticket_rejection_reason_label: 'Rejection Reason',
        ticket_info_staff: 'Your ticket is being processed according to the resort verification queue.',
        ticket_info_hod: 'As HOD, your approval will forward this ticket to Administrator.',
        ticket_info_admin: 'As Admin, your approval is Final ACC which immediately applies data to the system.',
        ticket_btn_reject_hod: 'Reject (HOD)',
        ticket_btn_approve_hod: 'HOD Approve (Forward to Admin)',
        ticket_btn_reject_admin: 'Reject Ticket',
        ticket_btn_approve_admin: 'Final ACC (Admin)',
        ticket_modal_confirm_title: 'Confirm Ticket Approval',
        ticket_modal_reject_title: 'Reject Ticket (Reason Required)',
        ticket_modal_ticket_num: 'Ticket Number',
        ticket_modal_applicant: 'Applicant',
        ticket_modal_type: 'Type',
        ticket_modal_reject_reason_label: 'Reason for Rejection',
        ticket_modal_reject_reason_placeholder: 'State the rejection reason clearly. This will be shown to the applicant...',
        ticket_modal_reject_reason_hint: 'This reason is required according to Telunas Resort audit standards.',
        ticket_modal_reject_reason_required: 'Rejection reason is required so the applicant understands why.',
        ticket_modal_notes_label: 'Approval Notes (Optional)',
        ticket_modal_notes_placeholder: 'Additional verification notes...',
        ticket_modal_btn_cancel: 'Cancel',
        ticket_modal_btn_confirm_approve: 'Confirm Approval',
        ticket_modal_btn_confirm_reject: 'Reject Ticket',
        ticket_modal_processing: 'Processing...',
        ticket_modal_error_default: 'An error occurred while processing ticket.',
        ticket_pdf_modal_title: 'Export Ticket Recapitulation PDF',
        ticket_pdf_modal_desc: 'Export complete approval ticket history with official Telunas Resorts format.',
        ticket_pdf_filter_status: 'Ticket Status Filter',
        ticket_pdf_filter_type: 'Ticket Type Filter',
        ticket_pdf_filter_dept: 'Department Filter',
        ticket_pdf_max_rows: 'Max Rows',
        ticket_pdf_download_btn: 'Download PDF Document',
        ticket_pdf_preview_loading: 'Preparing PDF preview...',
        ticket_pdf_doc_title: 'STAFF APPROVAL TICKET RECAPITULATION',
        ticket_pdf_doc_subtitle: 'Official Report of WhatsApp Change & Password Reset Authorizations',
        ticket_pdf_col_no: 'Ticket #',
        ticket_pdf_col_date: 'Date',
        ticket_pdf_col_type: 'Type',
        ticket_pdf_col_staff: 'Staff / Applicant',
        ticket_pdf_col_detail: 'Change Detail',
        ticket_pdf_col_status: 'Status',
        ticket_pdf_col_hod: 'HOD Review',
        ticket_pdf_col_admin: 'Admin ACC',
        ticket_pdf_generated_at: 'Document generated on',
        ticket_pdf_by_admin: 'by Admin',
        ticket_sync_success_toast: 'Successfully synced tickets to Google Sheet!',
        ticket_sync_failed_toast: 'Failed to sync Google Spreadsheet.',
        view_all_tickets: 'View All Approval Tickets',
        display_options: 'Card Display',
        location: 'Location',
        task_name: 'Task Name',
        status_icon: 'Status Icon',
        reset_display: 'Reset Display',
        pending_tasks: 'pending tasks',
        all_tasks_completed: 'All tasks completed',
    },
    id: {
        // Header & Nav
        system_title: 'Sistem Pelaporan Kerusakan',
        dashboard: 'Dashboard',
        analytics: 'Analistik',
        search_placeholder: 'Cari laporan atau lokasi...',
        search_analytics_placeholder: 'Cari aktivitas laporan terbaru...',
        search_calendar_placeholder: 'Cari tugas, tanggal, departemen...',
        tasks_found_across_dates: 'tugas ditemukan lintas tanggal',
        no_tasks_found: 'Tidak ada tugas ditemukan',
        jump_to_date: 'Lompat ke tanggal',
        status_finished: 'Selesai',
        status_unfinished: 'Aktif / Belum Selesai',
        period: 'Periode',
        export_pdf: 'Ekspor PDF',
        export_report: 'Ekspor Laporan',
        export_format_pdf: 'Dokumen PDF',
        export_format_excel: 'Excel (.xlsx)',
        download_excel: 'Unduh Excel (.xlsx)',
        generating_excel: 'Membuat Excel...',
        export_calendar_pdf: 'Ekspor Jadwal Kalender ke PDF',
        export_calendar_pdf_desc: 'Sesuaikan filter jadwal di sebelah kiri dan tinjau pratinjau PDF langsung di sebelah kanan.',
        schedule_period: 'Periode Jadwal',
        current_month: 'Bulan Ini',
        next_month: 'Bulan Depan',
        all_scheduled: 'Semua Jadwal',
        custom_range: 'Rentang Kustom',
        task_status: 'Status Tugas',
        grouping_and_order: 'Pengelompokan & Urutan',
        group_by_dept: 'Per Departemen',
        chronological: 'Urut Tanggal',
        report_options: 'Opsi Tambahan',
        include_kpi_summary: 'Tampilkan Kartu Ringkasan Metrik (KPI)',
        include_notes_column: 'Sertakan Kolom Catatan (Notes)',
        tasks_selected: 'tugas dipilih',
        generating_preview: 'Menyiapkan pratinjau...',
        download_pdf: 'Unduh PDF',
        downloading: 'Mengunduh...',
        send_via_email: 'Kirim via Email',
        email_report_title: 'Kirim Laporan via Email',
        email_recipients: 'Penerima Email',
        email_recipients_placeholder: 'Ketik email dan tekan Enter atau koma...',
        quick_select_recipients: 'Pilih Cepat Penerima',
        all_hods: 'Semua HOD',
        my_department: 'Departemen Saya',
        email_subject: 'Subjek Email',
        email_subject_placeholder: 'Subjek email laporan...',
        email_message: 'Catatan Pengirim (Opsional)',
        email_message_placeholder: 'Tambahkan pesan atau instruksi untuk penerima...',
        sending_email: 'Mengirimkan Email...',
        send_email_button: 'Kirim Email',
        email_sent_success: 'Laporan berhasil dikirimkan via email!',
        email_send_failed: 'Gagal mengirimkan email. Silakan periksa koneksi dan konfigurasi.',
        attached_pdf: 'Lampiran PDF',
        no_recipients_selected: 'Silakan pilih atau tambahkan minimal satu alamat email penerima.',
        google_connected_banner: 'Dikirim langsung dari Akun Google Anda:',
        google_not_connected_banner: 'Dikirim via Mailer Sistem Telunas',
        connect_google_button: 'Hubungkan Google',
        disconnect_google: 'Putuskan',
        connect_google_hint: 'Hubungkan akun Google Anda untuk mengirimkan laporan langsung dari Gmail pribadi.',
        select_multiple_hint: 'Bisa pilih lebih dari 1',
        emergency: 'DARURAT',
        report_issue: 'Buat Laporan',
        profile: 'Profil',

        // Dashboard Page
        facility_dashboard: 'Dashboard Fasilitas Komunitas',
        dashboard_desc: 'Laporkan kerusakan, klaim pekerjaan, dan catat perbaikan — terhubung langsung ke Google Sheets.',
        sync_sheets: 'Sinkronkan Sheets',
        total_reports: 'Total Laporan',
        needs_fixing: 'Perlu Perbaikan',
        in_progress: 'Dalam Proses',
        resolved: 'Terselesaikan',

        // Overdue Alert
        overdue_alert: 'LAPORAN KRITIS TERLAMBAT',
        unclaimed: 'Belum Diambil',
        unmute_alarm: 'Nyalakan Alarm',
        sound_active: 'Suara Aktif (Klik untuk Mute)',

        // Filters
        category: 'Kategori',
        department: 'Departemen',
        all: 'Semua',
        open: 'Terbuka',
        pending: 'Tertunda',
        solved: 'Selesai',
        all_categories: 'Semua Kategori',
        all_departments: 'Semua Departemen',
        filter_by_category: 'Filter berdasarkan Kategori',
        filter_by_dept: 'Filter berdasarkan Departemen',

        // Issue Card
        original_problem: 'Masalah Awal',
        reported_by: 'Dilaporkan oleh',
        currently_pending: 'Sedang ditunda oleh',
        claim_job: 'Ambil Pekerjaan',
        resolve_issue: 'Selesaikan Masalah',
        view_details: 'Lihat Detail',
        solved_details: 'Detail Penyelesaian',

        // Modals
        report_new_issue: 'Buat Laporan Baru',
        report_emergency: 'Laporkan Masalah DARURAT',
        location: 'Lokasi',
        title: 'Judul / Deskripsi',
        priority: 'Prioritas',
        photo: 'Foto',
        submit: 'Kirim Laporan',
        cancel: 'Batal',

        // Analytics
        performance_analytics: 'Analisis Kinerja & Penyelesaian',
        analytics_desc: 'Rincian metrik pemeliharaan resort, waktu respons, dan kinerja tim.',
        response_time: 'Rata-rata Waktu Respons',
        resolution_rate: 'Tingkat Penyelesaian',
        critical_issues: 'Masalah Kritis',
        department_breakdown: 'Rincian Departemen',
        category_distribution: 'Distribusi Kategori',

        // Analytics Page
        issues_by_category: 'Laporan per Kategori',
        issues_by_department: 'Laporan per Departemen',
        finished_status: 'Selesai',
        still_being_done: 'Sedang Dikerjakan',
        total_issues: 'Total Laporan',
        no_data: 'Tidak ada data',
        recent_activity: 'Aktivitas Laporan Terbaru',
        no_recent_activity: 'Belum ada aktivitas terbaru.',
        show: 'Tampilkan',
        items: 'Item',
        all_items: 'Semua',
        date_na: 'Tanggal N/A',
        critical: 'Kritis',
        by_reporter: 'oleh',
        photo_pending: '📷 Foto penundaan',
        photo_report: '📷 Foto laporan',
        select_sheets: 'Pilih Sheet Data',
        combine_sheets_desc: 'Pilih satu atau lebih sheet untuk melihat analisis gabungan lintas periode.',
        all_sheets: 'Semua Sheet',
        combining_sheets: 'Menggabungkan',
        sheets_label: 'sheet',
        active_issues_count: 'laporan dimuat',
        time_range: 'Rentang Waktu',
        filter_time_range: 'Filter Rentang Waktu',
        all_time: 'Semua Waktu',
        today: 'Hari Ini',
        days_3: '3 Hari',
        days_7: '7 Hari',
        week_1: '1 Minggu',
        weeks_2: '2 Minggu',
        weeks_3: '3 Minggu',
        weeks_4: '4 Minggu',
        month_1: '1 Bulan',
        months_3: '3 Bulan',
        year_1: '1 Tahun',
        showing_filtered_range: 'Menampilkan data untuk',

        // Departments & Assignment
        origin_department: 'Departemen Asal',
        assigned_departments: 'Departemen Ditugaskan',
        assigned_to: 'Ditugaskan Ke',
        responsible_to_fix: 'Bertanggung jawab memperbaiki',
        tagged_departments: 'Departemen Ditandai',
        tagged_info_only: 'Ditandai (Hanya Info / Notifikasi)',
        select_assigned_depts: 'Pilih departemen yang bertanggung jawab memperbaiki masalah ini',
        select_tagged_depts: 'Pilih departemen untuk diberitahu sebagai info / kewaspadaan saja',
        dept_filter_mode: 'Mode Filter',
        dept_mode_assigned: 'Dept Ditugaskan',
        dept_mode_origin: 'Dept Asal',
        dept_mode_tagged: 'Dept Ditandai',
        dept_mode_all: 'Semua Terkait',
        all_my_scope: 'Semua',
        to_fix: 'Tugas Masuk',
        reported_by_me: 'Laporan Saya',
        mentioned_me: 'Mention',
        dept_mode_incoming: 'Pekerjaan Masuk (Dikerjakan)',
        dept_mode_outgoing: 'Permintaan Keluar (Diajukan)',
        dept_mode_all_scope: 'Semua Relasi',
        dept_perspective_title: 'Perspektif Departemen',
        dept_perspective_desc: 'Menampilkan hubungan kerja departemen Anda dengan tim lain.',
        tooltip_incoming_dept: '📥 Tugas Masuk: Menampilkan departemen asal yang meminta bantuan atau menugaskan tiket ke departemen Anda.',
        tooltip_outgoing_dept: '📤 Permintaan Keluar: Menampilkan departemen tujuan yang ditugaskan untuk memperbaiki tiket yang diajukan departemen Anda.',
        tooltip_dept_all_scope: '🌐 Semua Relasi: Menampilkan seluruh departemen yang berinteraksi dengan departemen Anda.',

        // Operations Page
        operations: 'Operasional',
        select_department: 'Pilih Departemen',
        total_work: 'Total Pekerjaan',
        active_work: 'Pekerjaan Aktif',
        done_work: 'Selesai',
        pending_work: 'Tertunda / Laporan',
        refresh: 'Segarkan',
        add_work: 'Tambah Pekerjaan',
        add_work_for: 'Tambah Pekerjaan —',
        edit_work: 'Edit Pekerjaan',
        all_sources: 'Semua',
        source_issues: '🔧 Laporan Masalah (Issues)',
        source_manual: '📋 Tugas Departemen',
        select_sheets: 'Pilih Sheet / Periode',
        all_sheets: 'Semua Sheet',
        sheets_selected: 'dipilih',
        combined_sheets: 'Gabungan',
        loading_dept_data: 'Memuat data departemen…',
        no_active_work: 'Tidak ada pekerjaan aktif',
        no_active_work_desc: 'Klik "+ Tambah Pekerjaan" untuk menambahkan tugas departemen ini',
        work_title: 'Judul Pekerjaan',
        work_title_placeholder: 'cth: Perbaikan Hammock di Villa 01',
        work_desc: 'Deskripsi / Detail',
        work_desc_placeholder: 'Detail pekerjaan operasional atau pemeliharaan…',
        work_location: 'Lokasi',
        work_location_placeholder: 'cth: Villa 01, Area Pool, Dermaga Utama',
        specific_location_in: 'Detail di',
        start_date: 'Tanggal Mulai',
        end_date: 'Estimasi Selesai',
        priority_level: 'Prioritas',
        priority_low: 'Rendah',
        priority_normal: 'Normal',
        priority_urgent: 'Mendesak',
        priority_high: 'Tinggi',
        photo_optional: 'Unggah Foto (opsional)',
        notes: 'Catatan',
        notes_placeholder: 'Catatan tambahan atau keterangan…',
        save_work: 'Simpan Pekerjaan',
        save_changes: 'Simpan Perubahan',
        saving: 'Menyimpan…',
        mark_done: 'Selesai',
        edit: 'Edit',
        delete: 'Hapus',
        confirm_delete_work: 'Hapus pekerjaan ini?',
        created_at: 'Dibuat',
        completed_at: 'Selesai',
        from_dept: 'dari',
        claimed_at: 'Diklaim',
        pending_reason_title: 'Alasan Penundaan / Riwayat Pending',
        pending_by: 'Ditunda oleh',
        no_reason_provided: 'Tidak ada alasan tertera.',
        origin_badge: 'Asal',
        assigned_badge: 'Ditugaskan',
        tagged_badge: 'Ditandai',
        manual_badge: 'MANDIRI',
        issue_badge: 'LAPORAN',
        status_active: 'Aktif',
        status_needs_fixing: 'Perlu Perbaikan',
        status_in_progress: 'Sedang Dikerjakan',
        total_items_displayed: 'ditampilkan',
        work_summary_total: 'pekerjaan total',
        work_summary_active: 'aktif',
        work_summary_done: 'selesai',
        work_timeline: 'Timeline & Jadwal Kerja',
        timeline_schedule: 'Timeline & Target',
        days_remaining: 'hari tersisa',
        day_remaining: 'hari tersisa',
        days_overdue: 'hari terlambat',
        due_today: 'Target: Hari Ini',
        starts_in: 'Mulai dalam',
        calendar: 'Kalender',
        calendar_view: 'Kalender',
        list_view: 'Tampilan Daftar',
        calendar_mode: 'Mode Kalender',
        tasks_on_date: 'Tugas pada',
        task_unit: 'Tugas',
        task_unit_singular: 'Tugas',
        day_progress: 'Hari ke-{x} dari {y}',
        no_tasks_on_date: 'Tidak ada operasional atau tugas yang dijadwalkan pada hari ini',
        no_departments_selected: '0 Departemen Terpilih',
        single_day_task: 'Tugas 1 hari',
        today_btn: 'Hari Ini',
        add_work_on_date: 'Tambah Tugas di Tanggal Ini',
        selected_day_agenda: 'Agenda Harian',
        active_dept_calendar: 'Jadwal Kalender untuk',
        click_date_to_view: 'Klik tanggal untuk melihat rincian operasional',
        add_date_range: 'Tambah Rentang Tanggal',
        schedule_blocks: 'Rentang Jadwal',
        drag_hint_desktop: '💡 Klik & seret mouse pada kalender untuk memilih rentang tanggal',
        drag_calendar_tip: '💡 Seret mouse pada kalender untuk menambah atau memilih rentang jadwal',
        skipping_dates: 'Melewati',
        date_block: 'Rentang',
        block_start: 'Mulai',
        block_end: 'Sampai',
        focusing_on_task: 'Fokus Pada Tugas',
        show_all_tasks: 'Tampilkan Semua Tugas',
        task_focused_grid: 'Fokus di Kalender',
        click_card_to_view_grid: 'Klik blok untuk filter tanggal',
        click_block_to_filter: 'Klik blok untuk filter tanggal',
        all_blocks: 'Semua Blok',
        view_by_date: 'Tanggal',
        all_tasks_scope: 'Semua Tugas',
        back_to_date: 'Kembali ke Tanggal',
        months_label: 'Bulan',
        month_label: 'Bulan',
        all_time: 'Semua',
        clear_dates: 'Hapus Semua Tanggal',
        clear: 'Hapus',
        profile: 'Profil',
        logout: 'Keluar',
        account_settings: 'Akun & Keamanan',
        account_info: 'Informasi Akun',
        change_password: 'Ganti Kata Sandi',
        current_password: 'Kata Sandi Saat Ini',
        new_password: 'Kata Sandi Baru',
        confirm_password: 'Konfirmasi Kata Sandi Baru',
        password_changed_success: 'Kata sandi berhasil diperbarui.',
        role_label: 'Peran Akun',
        department_label: 'Cakupan Departemen',
        subdivision_label: 'Sub-Divisi',
        staff_name_label: 'Nama Tampilan',
        email_label: 'Alamat Email',
        confirm_logout_msg: 'Apakah Anda yakin ingin keluar dari perangkat ini?',
        logging_out: 'Sedang keluar...',

        // Locked Identity & Modals
        locked_to_department: 'Cakupan Departemen',
        claiming_department: 'Departemen Mengklaim',
        staff_name: 'Nama Petugas',
        assigned_staff: 'Petugas Bertugas',
        resolver_staff: 'Petugas Penyelesai',
        delay_staff: 'Petugas Pending',
        monitor_mode_title: 'Mode Pantau (Hanya Lihat)',
        monitor_mode_desc: 'Isu ini ditugaskan ke departemen lain. Hanya departemen tersebut yang dapat mengklaim atau menyelesaikan tiket ini.',
        step_dept_delay: 'Langkah 1 — Ditunda Oleh (Dept)',
        step_dept_resolve: 'Langkah 1 — Diselesaikan Oleh (Dept)',
        step_worker_delay: 'Langkah 2 — Nama Petugas',
        step_worker_resolve: 'Langkah 2 — Nama Petugas',
        proof_of_delay: 'Bukti Penundaan',
        proof_of_fix: 'Bukti Perbaikan',
        upload_proof_delay: 'Unggah bukti penundaan',
        upload_proof_fix: 'Unggah foto bukti perbaikan',
        confirm_pending: 'Konfirmasi Tertunda',
        mark_as_solved: 'Tandai Selesai',
        marking_pending: 'Menandai Tertunda...',
        saving_fix: 'Menyimpan Perbaikan...',
        cancel_pending_btn: 'Batalkan Tertunda, Tandai Selesai',
        mark_pending_btn: 'Ada kendala? Tandai Tertunda (Pending)',
        close_btn: 'Tutup',
        all_my_scope: 'Semua Terkait',
        to_fix: 'Pekerjaan Saya',
        reported_by_me: 'Dibuat Oleh Saya',
        mentioned_me: 'Mention Saya',

        // Schedule Conflict Warning
        schedule_conflict_title: 'Pemberitahuan Jadwal Departemen',
        schedule_conflict_desc: 'Departemen berikut memiliki jadwal tugas aktif pada hari ini:',
        schedule_conflict_confirm_title: 'Konfirmasi Penugasan ke Departemen yang Sedang Sibuk',
        schedule_conflict_confirm_msg: 'Departemen yang Anda pilih/tandai sedang memiliki jadwal tugas aktif pada rentang waktu ini. Apakah Anda yakin ingin tetap menugaskan laporan ini kepada mereka?',
        assign_anyway_btn: 'Ya, Tetap Tugaskan',
        review_assignment_btn: 'Tinjau Ulang Departemen',
        currently_busy_with: 'Sedang bertugas',
        active_task: 'Tugas Aktif',

        // Tooltip Explanations
        tooltip_assigned_dept: '🎯 Dept Ditugaskan: Menampilkan beban kerja berdasarkan departemen yang bertanggung jawab memperbaiki.',
        tooltip_origin_dept: '🏠 Dept Pelapor: Menampilkan departemen staf yang menemukan dan melaporkan masalah.',
        tooltip_tagged_dept: '📢 Dept Ditandai: Menampilkan departemen yang ditandai untuk koordinasi atau pemberitahuan.',
        tooltip_all_related_dept: '🌐 Semua Terkait: Menampilkan total keterlibatan (sebagai pelapor, pelaksana, maupun ditandai).',
        tooltip_sheet_selector: 'Pilih atau gabungkan sheet data antar periode/tahun.',
        tooltip_time_range: 'Filter laporan berdasarkan rentang waktu pelaporan.',
        tooltip_dept_limit: 'Pilih berapa banyak departemen teratas yang ditampilkan pada grafik.',
        tooltip_export_pdf: 'Unduh ringkasan analitik terfilter dalam format PDF.',
        tooltip_emergency_btn: 'Laporkan kerusakan darurat kritis dengan alarm suara.',
        tooltip_report_btn: 'Buat laporan baru kerusakan fasilitas atau pemeliharaan.',
        tooltip_period_btn: 'Pilih, buat, atau kelola periode data Google Sheets.',
        tooltip_claim_btn: 'Klaim tiket ini untuk mulai melakukan perbaikan.',
        tooltip_pending_btn: 'Tandai pending jika menunggu suku cadang atau bantuan khusus.',
        tooltip_resolve_btn: 'Unggah foto bukti selesai dan selesaikan tiket ini.',
        tooltip_today_btn: 'Kembali ke bulan dan tanggal hari ini.',
        tooltip_prev_month: 'Lihat jadwal bulan sebelumnya.',
        tooltip_next_month: 'Lihat jadwal bulan berikutnya.',

        // Profile WhatsApp Linking
        whatsapp_linking_title: 'Integrasi WhatsApp & Pengenalan Otomatis',
        whatsapp_number_label: 'Nomor WhatsApp Anda',
        save_whatsapp_btn: 'Simpan & Tautkan Nomor',
        update_whatsapp_btn: 'Perbarui Nomor WhatsApp',
        unlink_whatsapp_btn: 'Lepas Tautan Nomor',

        // Ticketing System
        tickets: 'Tiket',
        approval_tickets: 'Tiket Persetujuan',
        ticket_center_title: 'Pusat Persetujuan Tiket',
        ticket_admin_badge: 'ADMINISTRATOR — FINAL ACC',
        ticket_hod_badge: 'HOD',
        ticket_staff_badge: 'STAF',
        ticket_admin_desc: 'Pusat persetujuan tiket seluruh departemen Telunas Resort. Otorisasi final untuk mengaktifkan akun, nomor WhatsApp bot, dan reset password.',
        ticket_hod_desc: 'Tinjau dan verifikasi permohonan staf di naungan departemen Anda sebelum diteruskan ke Admin untuk ACC final.',
        ticket_staff_desc: 'Pantau status pengajuan permohonan nomor WhatsApp bot dan reset kata sandi akun Anda secara real-time.',
        ticket_pending_admin_acc: 'Perlu ACC Final',
        ticket_approved_count: 'Telah Disetujui',
        ticket_hod_review_count: 'Tinjauan HOD',
        ticket_my_tickets: 'Tiket Saya',
        ticket_active_tickets: 'Tiket Berjalan',
        ticket_total_requests: 'Total Pengajuan',
        ticket_two_tier_title: 'Alur Dua Tingkat:',
        ticket_two_tier_flow: '1. Pengajuan Staf ➔ 2. Verifikasi HOD Departemen ➔ 3. ACC Final Administrator',
        ticket_two_tier_flow_short: 'Staf ➔ HOD ➔ Admin ACC',
        ticket_banner_admin: 'Anda memiliki hak memberikan ACC Final & eksekusi langsung ke sistem.',
        ticket_banner_hod: 'Anda berwenang merekomendasikan tiket departemen Anda ke Admin.',
        ticket_banner_staff: 'Hubungi HOD atau Admin jika permohonan Anda memerlukan perhatian mendesak.',
        ticket_all_status: 'Semua Status',
        ticket_status_pending_hod: 'Menunggu HOD',
        ticket_status_pending_admin: 'Perlu ACC Admin',
        ticket_status_waiting_admin: 'Menunggu Admin',
        ticket_status_approved: 'Disetujui (ACC)',
        ticket_status_rejected: 'Ditolak',
        ticket_all_types: 'Semua Tipe',
        ticket_type_account_reg: 'Pendaftaran Akun',
        ticket_type_wa_change: 'Ganti WhatsApp',
        ticket_type_wa_unlink: 'Lepas WhatsApp',
        ticket_type_pwd_reset: 'Reset Password',
        ticket_type_dept_transfer: 'Pindah Departemen',
        ticket_search_placeholder: 'Cari tiket, staf, email...',
        ticket_refresh_btn: 'Refresh',
        ticket_export_pdf_btn: 'Export PDF',
        ticket_sync_sheet_btn: 'Sync Sheet',
        ticket_open_sheet_btn: 'Buka Google Spreadsheet Tiket',
        ticket_empty_title: 'Tidak Ada Tiket Ditemukan',
        ticket_empty_staff: 'Anda belum memiliki riwayat tiket aktif (perubahan nomor WhatsApp atau reset kata sandi).',
        ticket_empty_filter: 'Tidak ada permohonan tiket yang cocok dengan kriteria filter saat ini.',
        ticket_submitted_at: 'Diajukan',
        ticket_applicant: 'Pemohon',
        ticket_request_detail: 'Detail Permohonan',
        ticket_requested_wa: 'Nomor WhatsApp Diajukan',
        ticket_old_wa: 'Nomor Lama',
        ticket_requested: 'Diajukan',
        ticket_unlink_number: 'Lepas Nomor (Unlink)',
        ticket_pwd_reset_title: 'Permohonan Reset Kata Sandi',
        ticket_pwd_reset_hint: 'Kata sandi baru akan diaktifkan secara otomatis setelah disetujui Admin.',
        ticket_origin_dept: 'Asal',
        ticket_target_dept: 'Tujuan',
        ticket_reason_label: 'Alasan',
        ticket_audit_trail: 'Jejak Verifikasi',
        ticket_step_hod: '1. Tinjauan HOD',
        ticket_step_admin: '2. ACC Final Admin',
        ticket_completed: 'Selesai',
        ticket_by_label: 'Oleh',
        ticket_rejection_reason_label: 'Alasan Penolakan',
        ticket_info_staff: 'Tiket Anda diproses sesuai antrean verifikasi resort.',
        ticket_info_hod: 'Sebagai HOD, persetujuan Anda akan meneruskan tiket ini ke Administrator.',
        ticket_info_admin: 'Sebagai Admin, persetujuan Anda adalah ACC Final yang langsung mengaktifkan data ke sistem.',
        ticket_btn_reject_hod: 'Tolak (HOD)',
        ticket_btn_approve_hod: 'Setujui HOD (Teruskan ke Admin)',
        ticket_btn_reject_admin: 'Tolak Tiket',
        ticket_btn_approve_admin: 'ACC Final (Admin)',
        ticket_modal_confirm_title: 'Konfirmasi Persetujuan Tiket',
        ticket_modal_reject_title: 'Penolakan Tiket (Wajib Alasan)',
        ticket_modal_ticket_num: 'Nomor Tiket',
        ticket_modal_applicant: 'Pemohon',
        ticket_modal_type: 'Jenis',
        ticket_modal_reject_reason_label: 'Alasan Penolakan',
        ticket_modal_reject_reason_placeholder: 'Tuliskan alasan penolakan secara jelas. Alasan ini akan ditampilkan kepada pemohon...',
        ticket_modal_reject_reason_hint: 'Alasan ini wajib diisi sesuai standar audit Telunas Resort.',
        ticket_modal_reject_reason_required: 'Alasan penolakan wajib diisi agar pemohon mengetahuinya.',
        ticket_modal_notes_label: 'Catatan Persetujuan (Opsional)',
        ticket_modal_notes_placeholder: 'Catatan verifikasi tambahan...',
        ticket_modal_btn_cancel: 'Batal',
        ticket_modal_btn_confirm_approve: 'Konfirmasi Setujui',
        ticket_modal_btn_confirm_reject: 'Tolak Tiket',
        ticket_modal_processing: 'Memproses...',
        ticket_modal_error_default: 'Terjadi kesalahan saat memproses tiket.',
        ticket_pdf_modal_title: 'Ekspor PDF Rekapitulasi Tiket',
        ticket_pdf_modal_desc: 'Ekspor seluruh riwayat pengajuan dan verifikasi tiket staf dalam format resmi Telunas Resorts.',
        ticket_pdf_filter_status: 'Filter Status Tiket',
        ticket_pdf_filter_type: 'Filter Tipe Tiket',
        ticket_pdf_filter_dept: 'Filter Departemen',
        ticket_pdf_max_rows: 'Maksimal Baris',
        ticket_pdf_download_btn: 'Unduh Dokumen PDF',
        ticket_pdf_preview_loading: 'Menyiapkan pratinjau PDF...',
        ticket_pdf_doc_title: 'REKAPITULASI TIKET PERSETUJUAN STAF',
        ticket_pdf_doc_subtitle: 'Laporan Resmi Otorisasi Perubahan Nomor WhatsApp & Reset Kata Sandi',
        ticket_pdf_col_no: 'No. Tiket',
        ticket_pdf_col_date: 'Tanggal',
        ticket_pdf_col_type: 'Tipe Permohonan',
        ticket_pdf_col_staff: 'Staf / Pemohon',
        ticket_pdf_col_detail: 'Detail Perubahan',
        ticket_pdf_col_status: 'Status',
        ticket_pdf_col_hod: 'Tinjauan HOD',
        ticket_pdf_col_admin: 'ACC Admin',
        ticket_pdf_generated_at: 'Dokumen dicetak pada',
        ticket_pdf_by_admin: 'oleh Administrator',
        ticket_sync_success_toast: 'Berhasil menyinkronkan data tiket ke Google Spreadsheet!',
        ticket_sync_failed_toast: 'Gagal sinkronisasi spreadsheet.',
        view_all_tickets: 'Buka Semua Persetujuan Tiket',
        display_options: 'Tampilan Kartu',
        location: 'Lokasi',
        task_name: 'Nama Tugas',
        status_icon: 'Ikon Status',
        reset_display: 'Reset Tampilan',
        pending_tasks: 'tugas aktif tersisa',
        all_tasks_completed: 'Semua tugas selesai',
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [lang, setLangState] = useState(() => {
        return localStorage.getItem('app_lang') || 'en';
    });

    const setLang = (newLang) => {
        setLangState(newLang);
        localStorage.setItem('app_lang', newLang);
    };

    const t = (key) => {
        return translations[lang]?.[key] || translations.en?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
