<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $emailSubject }}</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #12110A;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            color: #E2DFD2;
            -webkit-font-smoothing: antialiased;
        }
        .container {
            max-width: 620px;
            margin: 30px auto;
            background-color: #1C1B0E;
            border-radius: 16px;
            border: 1px solid #3B3929;
            overflow: hidden;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
        }
        .header {
            background: linear-gradient(135deg, #1C1B0E 0%, #2A281E 100%);
            padding: 32px 30px 24px;
            border-bottom: 2px solid #C9AA71;
            text-align: center;
        }
        .logo-text {
            color: #C9AA71;
            font-size: 20px;
            font-weight: 800;
            letter-spacing: 2px;
            text-transform: uppercase;
            margin: 0;
        }
        .subtitle {
            color: #A19F8D;
            font-size: 12px;
            letter-spacing: 1px;
            text-transform: uppercase;
            margin-top: 4px;
        }
        .content {
            padding: 32px 30px;
        }
        .report-title {
            font-size: 19px;
            font-weight: 700;
            color: #FAFAFA;
            margin: 0 0 16px;
        }
        .meta-card {
            background-color: #242217;
            border: 1px solid #3B3929;
            border-radius: 12px;
            padding: 16px 20px;
            margin-bottom: 24px;
        }
        .meta-row {
            display: flex;
            justify-content: space-between;
            font-size: 13px;
            padding: 6px 0;
            border-bottom: 1px solid #2E2C1E;
        }
        .meta-row:last-child {
            border-bottom: none;
        }
        .meta-label {
            color: #A19F8D;
            font-weight: 500;
        }
        .meta-value {
            color: #FAFAFA;
            font-weight: 600;
        }
        .message-box {
            background-color: #2A281E;
            border-left: 3px solid #C9AA71;
            border-radius: 4px 8px 8px 4px;
            padding: 16px 18px;
            margin-bottom: 24px;
            font-size: 14px;
            line-height: 1.6;
            color: #E6E4D9;
        }
        .message-label {
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 1px;
            color: #C9AA71;
            margin-bottom: 6px;
        }
        .attachment-pill {
            display: inline-flex;
            align-items: center;
            background-color: #2D2615;
            border: 1px solid #C9AA71;
            border-radius: 10px;
            padding: 12px 18px;
            font-size: 13px;
            color: #F3E6C8;
            font-weight: 600;
            margin-bottom: 20px;
        }
        .attachment-icon {
            display: inline-block;
            margin-right: 8px;
            color: #C9AA71;
            font-size: 16px;
        }
        .footer {
            background-color: #16150B;
            border-top: 1px solid #2E2C1E;
            padding: 20px 30px;
            text-align: center;
            font-size: 12px;
            color: #716F60;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 6px;
            font-size: 11px;
            font-weight: 700;
            background-color: rgba(201, 170, 113, 0.2);
            color: #E5C384;
            margin-right: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <div class="header">
            <h1 class="logo-text">TELUNAS RESORTS</h1>
            <div class="subtitle">CampusFix • Issue Tracker Report</div>
        </div>

        <!-- Content -->
        <div class="content">
            <h2 class="report-title">{{ $emailSubject }}</h2>

            @if(!empty($customMessage))
                <div class="message-box">
                    <div class="message-label">Sender's Note from {{ $senderName }}</div>
                    <div>{!! nl2br(e($customMessage)) !!}</div>
                </div>
            @endif

            <!-- Report Summary -->
            <div class="meta-card">
                <table style="width: 100%; border-collapse: collapse;">
                    <tr style="border-bottom: 1px solid #2E2C1E;">
                        <td style="padding: 6px 0; color: #A19F8D; font-size: 13px;">Generated By</td>
                        <td style="padding: 6px 0; color: #FAFAFA; font-size: 13px; font-weight: 600; text-align: right;">
                            {{ $senderName }} ({{ $senderDepartment }})
                        </td>
                    </tr>
                    <tr style="border-bottom: 1px solid #2E2C1E;">
                        <td style="padding: 6px 0; color: #A19F8D; font-size: 13px;">Generated Date</td>
                        <td style="padding: 6px 0; color: #FAFAFA; font-size: 13px; font-weight: 600; text-align: right;">
                            {{ now()->format('d M Y, H:i') }}
                        </td>
                    </tr>
                    @if(!empty($reportMeta['scope']))
                    <tr style="border-bottom: 1px solid #2E2C1E;">
                        <td style="padding: 6px 0; color: #A19F8D; font-size: 13px;">Scope Filter</td>
                        <td style="padding: 6px 0; color: #FAFAFA; font-size: 13px; font-weight: 600; text-align: right;">
                            <span class="badge">{{ $reportMeta['scope'] }}</span>
                        </td>
                    </tr>
                    @endif
                    @if(!empty($reportMeta['sheets']))
                    <tr style="border-bottom: 1px solid #2E2C1E;">
                        <td style="padding: 6px 0; color: #A19F8D; font-size: 13px;">Sheet / Period</td>
                        <td style="padding: 6px 0; color: #FAFAFA; font-size: 13px; font-weight: 600; text-align: right;">
                            {{ is_array($reportMeta['sheets']) ? implode(', ', $reportMeta['sheets']) : $reportMeta['sheets'] }}
                        </td>
                    </tr>
                    @endif
                    @if(!empty($reportMeta['total_issues']))
                    <tr>
                        <td style="padding: 6px 0; color: #A19F8D; font-size: 13px;">Total Issues in Report</td>
                        <td style="padding: 6px 0; color: #C9AA71; font-size: 13px; font-weight: 700; text-align: right;">
                            {{ $reportMeta['total_issues'] }}
                        </td>
                    </tr>
                    @endif
                </table>
            </div>

            <!-- PDF Attachment Indicator -->
            <div class="attachment-pill">
                <span class="attachment-icon">📎</span>
                <span>Attached: <strong>{{ $pdfFilename }}</strong></span>
            </div>

            <p style="font-size: 13px; color: #A19F8D; margin: 0; line-height: 1.5;">
                The comprehensive PDF report has been attached to this email for your review and archival.
            </p>
        </div>

        <!-- Footer -->
        <div class="footer">
            <p style="margin: 0 0 6px;">This report was dispatched automatically from <strong>Telunas CampusFix Issue Tracker</strong>.</p>
            <p style="margin: 0;">Telunas Resorts • Private Island & Beach Resort</p>
        </div>
    </div>
</body>
</html>
